### ISSUE TITLE
t/152-pdfbuilder.t failures

### ISSUE THREAD

**Issue by eserte** [sciurius/perl-Text-Layout#11]
The test suite of 0.028 fails on most (maybe even all?) of my smokers if PDF::Builder is installed like this:
```
#   Failed test 'pixel_extents layout y -18'
#   at t/152-pdfbuilder.t line 111.

#   Failed test 'pixel_extents[0] ink y -18'
#   at t/152-pdfbuilder.t line 111.

#   Failed test 'pixel_extents[1] layout y -18'
#   at t/152-pdfbuilder.t line 111.

#   Failed test 'extents[0] ink y -18'
#   at t/152-pdfbuilder.t line 111.

#   Failed test 'extents[1] layout y -18'
#   at t/152-pdfbuilder.t line 111.
# Looks like you failed 5 tests of 31.
t/152-pdfbuilder.t .. 
Dubious, test returned 5 (wstat 1280, 0x500)
Failed 5/31 subtests 
```

**Comment by sciurius** [comment]
Thanks. Will be fixed in the next update.

**Comment by PhilterPaper** [comment]
Johan, anything need fixing on my end (PDF::Builder)? I could push out an emergency fix if necessary.

**Comment by sciurius** [comment]
No worries. One of the incompatible changes in this version of Text::Layout was the orientation of the extents (bounding boxes), and I forgot to adjust the PDF::Builder test for this.

If PDF::Builder uses Text::Layout extents it may be worth checking if that still works.

**Comment by PhilterPaper** [comment]
There's nothing _built into_ PDF::Builder to use Text::Layout. Aside from a vague mention of Text::Layout as possibly something of interest for PDF::Builder users, I've been waiting for it to settle down before actually incorporating it into Builder (if I end up doing that). See PhilterPaper/Perl-PDF-Builder#95 for some thoughts on the subject.

**Comment by PhilterPaper** [comment]
Version 0.029 appeared to install correctly on Windows, although perhaps you'd like to get an OK from @eserte before formally closing this.

**Comment by sciurius** [comment]
This should be fixed now, I see no build failures anymore in the CPAN Testers Matrix.
